### ISSUE TITLE
Problema ao usar InspectCar no alpine linux

### ISSUE THREAD

**Issue by Heyiamslice** [CollenMenezes/InspectCar#1]
Fui tentar fazer uma consulta pelo iSH mas apareceu uma mensagem de erro, tentei mais algumas vezes mas continua a mesma coisa
[
![image](https://user-images.githubusercontent.com/99917276/213765043-8d8b2bc3-1de8-4a99-b7b4-b0c0735f82f4.png)
](url)

**Comment by CollenMenezes** [comment]
Que estranho, foi de primeira esse erro?

**Comment by Heyiamslice** [comment]
pior q foi sim, tentei algumas vezes mas dava a mesma coisa

**Comment by Heyiamslice** [comment]
pior que foi sim, tentei algumas vezes e foi a mesma coisa

**Comment by CollenMenezes** [comment]
Até com uso de VPN?

**Comment by Heyiamslice** [comment]
aham, ios eh complicado

**Comment by CollenMenezes** [comment]
Não sei como funciona o Alpine, deve estar havendo algum problema nas requisições.
